name: Model CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-and-train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure
      - name: Minimal training run
        run: |
          if command -v nvidia-smi >/dev/null 2>&1; then
            nvidia-smi
          else
            echo "No GPU detected; running on CPU"
          fi
          pytest tests/test_train_model_pangu.py::test_train_model_runs_one_epoch -q
